### ISSUE TITLE
Precision targets for bootstrap functions

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/resample#131]
I worked out how to iterate the permutation tests until a precision target is reached.

It would be great to implement such a functionality also for the functions
- `bootstrap.bias`
- `bootstrap.bias_corrected`
- `bootstrap.variance`
- `bootstrap.confidence_interval`

This means adding keywords `precision` and `max_size` to the functions and to deprecate `size` (which would act like `max_size=size`, `precision=0`). We cannot do this for `bootstrap.bootstrap`, because we don't know what the user is computing.

With the keyword `return_error` (default False) we can optionally return the calculated uncertainty in a backward compatible way.

**Comment by amanmdesai** [comment]
Hi @HDembinski ,

I would be happy to work on this. Could you please guide me what do I need to do (and also please let me know any references on this topic ) ?

Thanks,
Aman

**Comment by HDembinski** [comment]
Hi Aman, thank you for your interest and the offer! I am trying to recover my thoughts of this issue, because I eventually abandoned this idea.

The problem is: the number of samples that need to be generated to achieve a given precision grows quadratically e.g. like `1/precision^2`. This means you get a huge increase in how many samples need to be generated if you go from a precision of 1 % to 0.1 %. I concluded that such an interface would just mislead users to pick a very small precision and then be surprised that it takes a very long time to compute the bootstrap result.

I will close this issue now.

**Comment by amanmdesai** [comment]
Oh I see.

**Comment by amanmdesai** [comment]
Hi @HDembinski 

Is there anything else that I can contribute to for this package

**Comment by HDembinski** [comment]
@amanmdesai Other than the other three open issues I have nothing on my mind right now. All three are not easy targets for a simple contribution, though. If you want to tackle one of them anyway, let me know, I can tell you what should be done. 

Otherwise, you may have some ideas on your own what could be improved in resample. Open a new issue if you want to discuss some idea for a new feature or improvement.

If you are not set on contributing to resample, but also open to contributing to other libraries: I am also maintaining iminuit, pyhepmc, numba-stats, and jacobi.
